// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClBqgjYYSCttHFvPgmJz2ZTiPgntzbHXw',
    appId: '1:322359519946:web:9ee05f1bfdfbc4fbc2e233',
    messagingSenderId: '322359519946',
    projectId: 'onlinechat-21970',
    authDomain: 'onlinechat-21970.firebaseapp.com',
    storageBucket: 'onlinechat-21970.appspot.com',
    measurementId: 'G-2E7PQ0J7FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeLBIqCkhb2HT4EW6L6b5ItG3jTX8UXtk',
    appId: '1:322359519946:android:3f9e3928a7472125c2e233',
    messagingSenderId: '322359519946',
    projectId: 'onlinechat-21970',
    storageBucket: 'onlinechat-21970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPiijpU_UwR3c3mGYK4h09KfvwRMnGn4A',
    appId: '1:322359519946:ios:b76ff7cf6526845bc2e233',
    messagingSenderId: '322359519946',
    projectId: 'onlinechat-21970',
    storageBucket: 'onlinechat-21970.appspot.com',
    iosClientId: '322359519946-o8mk2703c336skc9bg76pq8o6vb9m2h5.apps.googleusercontent.com',
    iosBundleId: 'com.hafizramiz.onlineChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPiijpU_UwR3c3mGYK4h09KfvwRMnGn4A',
    appId: '1:322359519946:ios:b76ff7cf6526845bc2e233',
    messagingSenderId: '322359519946',
    projectId: 'onlinechat-21970',
    storageBucket: 'onlinechat-21970.appspot.com',
    iosClientId: '322359519946-o8mk2703c336skc9bg76pq8o6vb9m2h5.apps.googleusercontent.com',
    iosBundleId: 'com.hafizramiz.onlineChat',
  );
}
